services:
  app_proxy:
    environment:
      APP_HOST: app
      APP_PORT: 3000
  app:
    image: docker.gitea.com/gitea:1.27.1-rootless@sha256:36cce26be71609091e1236d5b5de2c66a81fb8a7d45756a5fd3b7a28c11733b7
    restart: unless-stopped
    ports:
      - 127.0.0.1:33028:3000
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/gitea
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
